# Generated by Django 3.2.8 on 2021-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
